// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api/v1/users.proto

/*
Package api_v1 is a generated protocol buffer package.

It is generated from these files:
	proto/api/v1/users.proto

It has these top-level messages:
	ListUsersRequest
	ListUsersResponse
	GetUserRequest
	CreateUserRequest
	UpdateUserRequest
	UpdateUserResponse
	DeleteUserRequest
	DeleteUserResponse
	User
*/
package api_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListUsersRequest struct {
}

func (m *ListUsersRequest) Reset()                    { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()               {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ListUsersResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *ListUsersResponse) Reset()                    { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()               {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetUserRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateUserRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	RealName string `protobuf:"bytes,2,opt,name=real_name,json=realName" json:"real_name,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

type UpdateUserRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateUserResponse struct {
}

func (m *UpdateUserResponse) Reset()                    { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()               {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type DeleteUserRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteUserResponse struct {
}

func (m *DeleteUserResponse) Reset()                    { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()               {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type User struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	RealName string `protobuf:"bytes,3,opt,name=real_name,json=realName" json:"real_name,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func init() {
	proto.RegisterType((*ListUsersRequest)(nil), "api.v1.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "api.v1.ListUsersResponse")
	proto.RegisterType((*GetUserRequest)(nil), "api.v1.GetUserRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "api.v1.CreateUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "api.v1.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "api.v1.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "api.v1.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "api.v1.DeleteUserResponse")
	proto.RegisterType((*User)(nil), "api.v1.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Users service

type UsersClient interface {
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := grpc.Invoke(ctx, "/api.v1.Users/ListUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/api.v1.Users/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/api.v1.Users/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := grpc.Invoke(ctx, "/api.v1.Users/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := grpc.Invoke(ctx, "/api.v1.Users/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersServer interface {
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Users/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Users/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Users/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Users/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Users/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _Users_ListUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Users_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Users_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Users_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Users_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api/v1/users.proto",
}

func init() { proto.RegisterFile("proto/api/v1/users.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0xfa, 0x47, 0x33, 0x95, 0xd0, 0x8c, 0xa5, 0xa4, 0xd1, 0x43, 0x59, 0x2f, 0xa5,
	0x87, 0x84, 0xd6, 0x83, 0xe0, 0xd5, 0x42, 0x0f, 0x8a, 0x87, 0x4a, 0x4f, 0x82, 0xb2, 0x92, 0xa5,
	0x04, 0xda, 0x24, 0x26, 0x69, 0x2f, 0xe2, 0xc5, 0x57, 0xf0, 0x41, 0x7c, 0x18, 0x5f, 0xc1, 0x07,
	0x91, 0xdd, 0x6e, 0xb3, 0x49, 0x5a, 0xc4, 0x5b, 0xb2, 0xf3, 0x7d, 0xbf, 0x9d, 0x99, 0x2f, 0x01,
	0x3b, 0x4e, 0xa2, 0x2c, 0xf2, 0x68, 0x1c, 0x78, 0x9b, 0x91, 0xb7, 0x4e, 0x59, 0x92, 0xba, 0xe2,
	0x08, 0x9b, 0x34, 0x0e, 0xdc, 0xcd, 0xc8, 0x39, 0x5f, 0x44, 0xd1, 0x62, 0xc9, 0x84, 0x84, 0x86,
	0x61, 0x94, 0xd1, 0x2c, 0x88, 0x42, 0xa9, 0x22, 0x08, 0xed, 0xbb, 0x20, 0xcd, 0xe6, 0xdc, 0x38,
	0x63, 0xaf, 0x6b, 0x96, 0x66, 0xe4, 0x0a, 0xac, 0xc2, 0x59, 0x1a, 0x47, 0x61, 0xca, 0x90, 0x40,
	0x43, 0xd0, 0x6d, 0xad, 0x5f, 0x1b, 0xb4, 0xc6, 0x27, 0xee, 0x16, 0xef, 0x72, 0xd5, 0x6c, 0x5b,
	0x22, 0x7d, 0x30, 0xa7, 0x4c, 0xf8, 0x24, 0x0a, 0x4d, 0xd0, 0x03, 0xdf, 0xd6, 0xfa, 0xda, 0xc0,
	0x98, 0xe9, 0x81, 0x4f, 0x26, 0x60, 0xdd, 0x24, 0x8c, 0x66, 0xac, 0x28, 0x42, 0xa8, 0x87, 0x74,
	0xc5, 0xa4, 0x4c, 0x3c, 0xe3, 0x19, 0x18, 0x09, 0xa3, 0xcb, 0x67, 0x51, 0xd0, 0x45, 0xe1, 0x98,
	0x1f, 0xdc, 0xd3, 0x15, 0xe3, 0x0d, 0xce, 0x63, 0xbf, 0x42, 0xa9, 0x5c, 0x95, 0x53, 0x75, 0x45,
	0x25, 0x1d, 0xc0, 0xa2, 0x71, 0x3b, 0x1a, 0xb9, 0x00, 0x6b, 0xc2, 0x96, 0xec, 0x4f, 0x1c, 0xb7,
	0x16, 0x45, 0xd2, 0x3a, 0x85, 0x3a, 0x7f, 0xff, 0xcf, 0xe5, 0xe5, 0x91, 0x6a, 0xe5, 0x91, 0xc6,
	0x5f, 0x35, 0x68, 0x88, 0x85, 0xe3, 0x03, 0x18, 0xf9, 0xf6, 0xd1, 0xde, 0xad, 0xb9, 0x1a, 0x92,
	0xd3, 0x3b, 0x50, 0x91, 0x4d, 0x59, 0x1f, 0xdf, 0x3f, 0x9f, 0x7a, 0x0b, 0x8d, 0xfc, 0x93, 0xc0,
	0x29, 0x1c, 0xc9, 0x64, 0xb0, 0xbb, 0x33, 0x96, 0xa3, 0x72, 0x4a, 0x89, 0x92, 0xae, 0x60, 0xb4,
	0xd1, 0xcc, 0x19, 0xde, 0x5b, 0xe0, 0xbf, 0xe3, 0x2d, 0x80, 0x0a, 0x10, 0xf3, 0x26, 0xf6, 0x42,
	0xad, 0xe0, 0x3a, 0x02, 0x67, 0x12, 0xd5, 0xd2, 0xb5, 0x36, 0xc4, 0x27, 0x00, 0x15, 0x87, 0x82,
	0xed, 0x65, 0xeb, 0x38, 0x87, 0x4a, 0x72, 0xda, 0x9e, 0x40, 0x9f, 0x3a, 0x95, 0x4e, 0x39, 0xff,
	0x11, 0x40, 0x65, 0xa6, 0xf8, 0x7b, 0x61, 0x2b, 0xfe, 0x81, 0x88, 0xe5, 0x26, 0x86, 0x15, 0xfe,
	0x4b, 0x53, 0xfc, 0x40, 0x97, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xae, 0xef, 0xcf, 0x82,
	0x03, 0x00, 0x00,
}
